### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [14]:
# np.array
import numpy as np

a = np.array([1,2,3, 15])
print(a, type(a), type(a[0]))

b = np.array(['Nehul'])
c = np.array2string(a)
print(b, type(b))
print(c, type(c))

print(a[2])
print(c[0])

print()
for i in a:
  print(i, end=' ')
print()
for i in c:
  print(i, end=' ')

print()
print(len(c))

[ 1  2  3 15] <class 'numpy.ndarray'> <class 'numpy.int64'>
['Nehul'] <class 'numpy.ndarray'>
[ 1  2  3 15] <class 'str'>
3
[

1 2 3 15 
[   1     2     3   1 5 ] 
13


In [3]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype
a = np.array([1,2,3],dtype=float)
print(a, type(a), type(a[0]))

b = np.array([1.2, 2, 3, 4])
print(b, type(b), type(b[0]))

c = np.array([0,1,2,3], dtype=bool)
print(c)

[1. 2. 3.] <class 'numpy.ndarray'> <class 'numpy.float64'>
[1.2 2.  3.  4. ] <class 'numpy.ndarray'> <class 'numpy.float64'>
[False  True  True  True]


In [6]:
# np.arange
print(np.arange(1,11,2))
print(np.arange(1,11))

[1 3 5 7 9]
[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
# with reshape
print(np.arange(1,11).reshape(5,2))
print()
print(np.arange(1,13).reshape(3,4))
print()
print(np.arange(16).reshape(2,2,2,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [8]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.29256802, 0.58100523, 0.00215885, 0.76088814],
       [0.13057955, 0.36575121, 0.38134471, 0.87150986],
       [0.59479334, 0.35473515, 0.55118816, 0.33660028]])

In [ ]:
# np.linspace
print(np.linspace(11,20,10))
print(np.linspace(-10,10,10,dtype=int))

[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
[-10  -8  -6  -4  -2   1   3   5   7  10]


In [ ]:
# np.identity
print(np.identity(3, dtype=int))
print()
print(np.identity(3))

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Array Attributes

In [3]:
import numpy as np

a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [4]:
# ndim
a3.ndim

3

In [9]:
# shape
print(a1.shape)
print(a3.shape)
a3

(10,)
(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [10]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [11]:
# itemsize
a3.itemsize

8

In [12]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [19]:
# astype
print(a3.dtype)
print(a3.astype(np.int32))
print(a3.dtype)

int64
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
int64


### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [22]:
a1 = np.random.random((3,3))
print(a1)
a1 = np.round(a1*100)
print()
print(a1)

[[0.86271452 0.85905935 0.80728158]
 [0.61291055 0.27132795 0.37095406]
 [0.37167041 0.58585289 0.66802793]]

[[86. 86. 81.]
 [61. 27. 37.]
 [37. 59. 67.]]


In [40]:
# max/min/sum/prod
print(a1.max())
print(np.max(a1))

print(np.min(a1))
print(a1.min(1)) # har row mein min value kya hai

print(np.sum(a1))
print(a1.sum())

print(np.prod(a1))
print(a1.prod())

# 0 -> col and 1 -> row
print(np.max(a1, axis=1)) # har row mein max value kya hai
print(a1.max(axis=1))
print(np.min(a1, axis=1)) # har row mein min value kya hai
print(a1.max(axis=1))

print(np.prod(a1,axis=0))

86.0
86.0
27.0
[81. 27. 37.]
541.0
541.0
5339563836251004.0
5339563836251004.0
[86. 61. 67.]
[86. 61. 67.]
[81. 27. 37.]
[86. 61. 67.]
[194102. 136998. 200799.]


In [47]:
# mean/median/std/var
print(np.mean(a1))
print(np.mean(a1, axis=1)) # har row ka mean

print(np.median(a1))
print(np.median(a1, axis=1))

print(np.std(a1))
print(np.std(a1, axis=1))

print(np.var(a1))
np.var(a1,axis=1)

60.111111111111114
[84.33333333 41.66666667 54.33333333]
61.0
[86. 37. 59.]
21.05782749396129
[ 2.3570226  14.26728971 12.68419839]
443.4320987654321


array([  5.55555556, 203.55555556, 160.88888889])

In [49]:
# trigonomoetric functions
np.sin(a1)

array([[-0.92345845, -0.92345845, -0.62988799],
       [-0.96611777,  0.95637593, -0.64353813],
       [-0.64353813,  0.63673801, -0.85551998]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [51]:
# log and exponents
print(np.log(a1))
print()
print(np.exp(a1))

[[4.4543473  4.4543473  4.39444915]
 [4.11087386 3.29583687 3.61091791]
 [3.61091791 4.07753744 4.20469262]]

[[2.23524660e+37 2.23524660e+37 1.50609731e+35]
 [3.10429794e+26 5.32048241e+11 1.17191424e+16]
 [1.17191424e+16 4.20121040e+25 1.25236317e+29]]


In [53]:
# round/floor/ceil
ax = np.random.random((2,3))*100
print(ax)
print(np.round(ax))
print(np.floor(ax))
np.ceil(ax)

[[53.72664134 57.73653696  8.72651096]
 [ 7.27898995 78.46937651 74.83997884]]
[[54. 58.  9.]
 [ 7. 78. 75.]]
[[53. 57.  8.]
 [ 7. 78. 74.]]


array([[54., 58.,  9.],
       [ 8., 79., 75.]])

### Indexing and Slicing

In [56]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [57]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
print(a1[-1])
print(a1[0])

9
0


In [61]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
print(a2[1][2])
print(a2[1,2])
print(a2[2,3])

6
6
11


In [63]:
a2[1,0]

np.int64(4)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [69]:
print(a3[1][0][1])
print(a3[1,0,1])

5
5


In [ ]:
a3[1,0,1]

5

In [ ]:
a3[1,1,0]

6

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [74]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
print(a2[::2,1::2])
print()
print(a2[1:2,::3])
print()
print(a2[:2,1:])

[[ 1  3]
 [ 9 11]]

[[4 7]]

[[1 2 3]
 [5 6 7]]


In [78]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [88]:
print(a3[1])
print('\n')
print(a3[::2])
print('\n')
print(a3[0,1,:])
print('\n')
print(a3[1,:,1])
print('\n')
print(a3[2,1:,1:])
print('\n')
print(a3[::2,0,::2])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[3 4 5]


[10 13 16]


[[22 23]
 [25 26]]


[[ 0  2]
 [18 20]]


In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [ ]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [89]:
for i in a2:
  for j in i:
    print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [ ]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [93]:
# ravel
a3.ravel()
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [1]:
# horizontal stacking
import numpy as np
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [2]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [3]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [4]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
print(np.hsplit(a4,2))
print('\n')
print(np.hsplit(a4,4))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [6]:
np.hsplit(a4,5)

ValueError: array split does not result in an equal division

In [7]:
# vertical splitting

In [8]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [9]:
np.vsplit(a5,2)

ValueError: array split does not result in an equal division