### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([29, 11, 52, 48, 55, 17, 78, 96, 34, 18, 68, 40, 71, 22, 67])

In [2]:
# a = np.linspace(10, 20,100, dtype=int)
# # a = np.random.randint(10,20, 100)
# a

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[20, 79, 54, 38],
       [16, 62, 54, 82],
       [30, 75,  1, 86],
       [ 6, 79,  8, 41],
       [97, 30, 82, 65],
       [ 1,  3, 98, 61]])

In [4]:
print(np.sort(a))
print(np.sort(b)) # it sort row wise
print(np.sort(b, axis=0)) # sort column wise
np.sort(a)[::-1]

[11 17 18 22 29 34 40 48 52 55 67 68 71 78 96]
[[20 38 54 79]
 [16 54 62 82]
 [ 1 30 75 86]
 [ 6  8 41 79]
 [30 65 82 97]
 [ 1  3 61 98]]
[[ 1  3  1 38]
 [ 6 30  8 41]
 [16 62 54 61]
 [20 75 54 65]
 [30 79 82 82]
 [97 79 98 86]]


array([96, 78, 71, 68, 67, 55, 52, 48, 40, 34, 29, 22, 18, 17, 11])

In [5]:
np.sort(b,axis=0)

array([[ 1,  3,  1, 38],
       [ 6, 30,  8, 41],
       [16, 62, 54, 61],
       [20, 75, 54, 65],
       [30, 79, 82, 82],
       [97, 79, 98, 86]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
# code
np.append(a,200)

array([ 29,  11,  52,  48,  55,  17,  78,  96,  34,  18,  68,  40,  71,
        22,  67, 200])

In [7]:
b

array([[20, 79, 54, 38],
       [16, 62, 54, 82],
       [30, 75,  1, 86],
       [ 6, 79,  8, 41],
       [97, 30, 82, 65],
       [ 1,  3, 98, 61]])

In [8]:
# np.append(b,np.random.random((b.shape[0],1)),axis=1)
# np.append(b,np.ones((b.shape[0],1), dtype=int),axis=1)
np.append(b, np.arange(b.shape[0]).reshape(b.shape[0],1), axis=1)
# np.append(b, np.arange(b.shape[0]).reshape(1, b.shape[-1]), axis=1) # error

array([[20, 79, 54, 38,  0],
       [16, 62, 54, 82,  1],
       [30, 75,  1, 86,  2],
       [ 6, 79,  8, 41,  3],
       [97, 30, 82, 65,  4],
       [ 1,  3, 98, 61,  5]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [9]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [10]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [12]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [13]:
np.unique(e)
np.unique(e,return_index=True, return_counts=True)

(array([1, 2, 3, 4, 5, 6]),
 array([ 0,  2,  4,  6,  8, 10]),
 array([2, 2, 2, 2, 2, 2]))

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [14]:
# code
a.shape

(15,)

In [15]:
x = np.expand_dims(a,axis=0)
print(x)
x.shape

[[29 11 52 48 55 17 78 96 34 18 68 40 71 22 67]]


(1, 15)

In [16]:
np.expand_dims(a,axis=1)

array([[29],
       [11],
       [52],
       [48],
       [55],
       [17],
       [78],
       [96],
       [34],
       [18],
       [68],
       [40],
       [71],
       [22],
       [67]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [17]:
a

array([29, 11, 52, 48, 55, 17, 78, 96, 34, 18, 68, 40, 71, 22, 67])

In [18]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 2,  4,  6,  7, 10, 12, 14]),)

In [19]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([29, 11,  0, 48,  0, 17,  0,  0, 34, 18,  0, 40,  0, 22,  0])

In [20]:
np.where(a%2 == 0,0,a)

array([29, 11,  0,  0, 55, 17,  0,  0,  0,  0,  0,  0, 71,  0, 67])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [21]:
# code
a

array([29, 11, 52, 48, 55, 17, 78, 96, 34, 18, 68, 40, 71, 22, 67])

In [22]:
import numpy as np
np.argmax(a)

np.int64(7)

In [23]:
b

array([[20, 79, 54, 38],
       [16, 62, 54, 82],
       [30, 75,  1, 86],
       [ 6, 79,  8, 41],
       [97, 30, 82, 65],
       [ 1,  3, 98, 61]])

In [24]:
np.argmax(b,axis=0)

array([4, 0, 5, 2])

In [25]:
np.argmax(b,axis=1)

array([1, 3, 3, 1, 0, 2])

In [26]:
# np.argmin
np.argmin(a)

np.int64(1)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [27]:
a

array([29, 11, 52, 48, 55, 17, 78, 96, 34, 18, 68, 40, 71, 22, 67])

In [28]:
np.cumsum(a)

array([ 29,  40,  92, 140, 195, 212, 290, 386, 420, 438, 506, 546, 617,
       639, 706])

In [29]:
b

array([[20, 79, 54, 38],
       [16, 62, 54, 82],
       [30, 75,  1, 86],
       [ 6, 79,  8, 41],
       [97, 30, 82, 65],
       [ 1,  3, 98, 61]])

In [30]:
np.cumsum(b,axis=1)

array([[ 20,  99, 153, 191],
       [ 16,  78, 132, 214],
       [ 30, 105, 106, 192],
       [  6,  85,  93, 134],
       [ 97, 127, 209, 274],
       [  1,   4, 102, 163]])

In [31]:
np.cumsum(b)

array([  20,   99,  153,  191,  207,  269,  323,  405,  435,  510,  511,
        597,  603,  682,  690,  731,  828,  858,  940, 1005, 1006, 1009,
       1107, 1168])

In [32]:
# np.cumprod
np.cumprod(a)

array([                  29,                  319,                16588,
                     796224,             43792320,            744469440,
                58068616320,        5574587166720,      189535963668480,
           3411647346032640,   231992019530219520, -9167063292500770816,
       -5225451187720421376, -4279461687591960576,  8423972110691467264])

In [33]:
a

array([29, 11, 52, 48, 55, 17, 78, 96, 34, 18, 68, 40, 71, 22, 67])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [34]:
a

array([29, 11, 52, 48, 55, 17, 78, 96, 34, 18, 68, 40, 71, 22, 67])

In [35]:
np.percentile(a,50)

np.float64(48.0)

In [36]:
np.median(a)

np.float64(48.0)

In [37]:
b

array([[20, 79, 54, 38],
       [16, 62, 54, 82],
       [30, 75,  1, 86],
       [ 6, 79,  8, 41],
       [97, 30, 82, 65],
       [ 1,  3, 98, 61]])

In [38]:
np.percentile(b,100,axis=1)

array([79., 82., 86., 79., 97., 98.])

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [39]:
# code
a

array([29, 11, 52, 48, 55, 17, 78, 96, 34, 18, 68, 40, 71, 22, 67])

In [40]:
np.histogram(a, bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 3, 2, 1, 2, 2, 2, 2, 0, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [43]:
np.histogram(a,bins=[0,50,100])

(array([8, 7]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [44]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [45]:
# code
a


array([29, 11, 52, 48, 55, 17, 78, 96, 34, 18, 68, 40, 71, 22, 67])

In [47]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([40])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [48]:
# code
a

array([29, 11, 52, 48, 55, 17, 78, 96, 34, 18, 68, 40, 71, 22, 67])

In [49]:
np.flip(a)

array([67, 22, 71, 40, 68, 18, 34, 96, 78, 17, 55, 48, 52, 11, 29])

In [61]:
b

array([[20, 79, 54, 38],
       [16, 62, 54, 82],
       [30, 75,  1, 86],
       [ 6, 79,  8, 41],
       [97, 30, 82, 65],
       [ 1,  3, 98, 61]])

In [60]:
np.flip(b)

array([[61, 98,  3,  1],
       [65, 82, 30, 97],
       [41,  8, 79,  6],
       [86,  1, 75, 30],
       [82, 54, 62, 16],
       [38, 54, 79, 20]])

In [55]:
np.flip(b, axis=1)

array([[38, 54, 79, 20],
       [82, 54, 62, 16],
       [86,  1, 75, 30],
       [41,  8, 79,  6],
       [65, 82, 30, 97],
       [61, 98,  3,  1]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.put(a,[0,1],[110,530])

In [69]:
np.put(b,[0,2],[1200])
b

array([[1200,  500, 1200,   38],
       [  16,   62,   54,   82],
       [  30,   75,    1,   86],
       [   6,   79,    8,   41],
       [  97,   30,   82,   65],
       [   1,    3,   98,   61]])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [73]:
# code
a

array([29, 11, 52, 48, 55, 17, 78, 96, 34, 18, 68, 40, 71, 22, 67])

In [72]:
np.delete(a,[0,2,4])

array([11, 48, 17, 78, 96, 34, 18, 68, 40, 71, 22, 67])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [77]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

print(np.union1d(m,n))
print(np.unique_counts((m,n)))

[1 2 3 4 5 6 7]
UniqueCountsResult(values=array([1, 2, 3, 4, 5, 6, 7]), counts=array([1, 1, 2, 2, 2, 1, 1]))


In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n) # dono ke common ko hatha dega and baki ko rakh lega

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 50, 38, 37, 75, 75, 25, 30, 68, 25, 75, 25, 25])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [78]:

# 25. np.allclose and equals